fail build if no changelog found

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -26,6 +26,15 @@ jobs:
         - /home/travis/build/chromedriver --version
         - env webdriver.chrome.driver=/home/travis/build/
         - SDK_VERSION=$(echo $TRAVIS_TAG | sed 's/[^.0-9]*//g')
+        - chmod +x ./extractChangeLog.sh
+        - TMP_CHANGELOG=$(./extractChangeLog.sh "$SDK_VERSION" "CHANGELOG.md")
+        - echo "$TMP_CHANGELOG"
+        - CHANGELOG=$([ -z "$TMP_CHANGELOG" ] && echo "ERROR: There is no change log for version $SDK_VERSION" || echo "$TMP_CHANGELOG")
+        - echo $CHANGELOG
+        - if [ -z "$TMP_CHANGELOG" ]; then
+          sleep 5;
+          exit 1;
+          fi
         - if [[ $TRAVIS_TAG =~ ^RELEASE_CANDIDATE ]]; then
           git remote set-url origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG};
           mvn versions:set -DnewVersion=$SDK_VERSION;
